version: "3.9"

services:
  app:
    build: .
    container_name: spark-log-transformer
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python web_server_access_log_analysis.py